package sqlexport

import (
	"strings"
	"testing"

	"github.com/headercat/erdn-lang/internal/parser"
	"github.com/headercat/erdn-lang/internal/semantic"
)

func generateSQL(t *testing.T, src string, dbms DBMS) string {
	t.Helper()
	prog, err := parser.ParseString(src)
	if err != nil {
		t.Fatalf("parse error: %v", err)
	}
	errs := semantic.Validate(prog)
	if len(errs) > 0 {
		t.Fatalf("validation errors: %v", errs)
	}
	return Generate(prog, dbms)
}

const blogSchema = `
table authors (
  id       bigint      primary-key auto-increment
  username varchar(64) not-null indexed
  email    varchar(255) not-null indexed
  bio      text        nullable
)

table posts (
  id        bigint       primary-key auto-increment
  author_id bigint       not-null indexed
  title     varchar(512) not-null
  status    varchar(32)  not-null default("draft")
  created_at timestamp   not-null default(NOW())
)

link one authors.id to many posts.author_id
`

func TestValidDBMS(t *testing.T) {
	for _, name := range SupportedDBMS {
		if !ValidDBMS(name) {
			t.Errorf("ValidDBMS(%q) = false, want true", name)
		}
	}
	if ValidDBMS("unknown") {
		t.Error("ValidDBMS(\"unknown\") = true, want false")
	}
}

func TestGenerateHeader(t *testing.T) {
	for _, dbms := range []DBMS{DBMSMySQL, DBMSPostgreSQL, DBMSMSSQL, DBMSOracle, DBMSSQLite} {
		out := generateSQL(t, `table t (id bigint primary-key)`, dbms)
		if !strings.Contains(out, "-- Generated by erdn-lang") {
			t.Errorf("DBMS %s: missing header comment", dbms)
		}
		if !strings.Contains(out, string(dbms)) {
			t.Errorf("DBMS %s: missing DBMS name in header", dbms)
		}
	}
}

func TestGenerateMySQL(t *testing.T) {
	out := generateSQL(t, blogSchema, DBMSMySQL)

	// Identifier quoting
	if !strings.Contains(out, "`authors`") {
		t.Error("MySQL: expected backtick-quoted table name `authors`")
	}
	// AUTO_INCREMENT
	if !strings.Contains(out, "AUTO_INCREMENT") {
		t.Error("MySQL: expected AUTO_INCREMENT")
	}
	// Type mappings
	if !strings.Contains(out, "VARCHAR(64)") {
		t.Error("MySQL: expected VARCHAR(64)")
	}
	if !strings.Contains(out, "TIMESTAMP") {
		t.Error("MySQL: expected TIMESTAMP")
	}
	// Default string conversion
	if !strings.Contains(out, "DEFAULT 'draft'") {
		t.Error("MySQL: expected DEFAULT 'draft'")
	}
	// NOW() preserved
	if !strings.Contains(out, "DEFAULT NOW()") {
		t.Error("MySQL: expected DEFAULT NOW()")
	}
	// Primary key constraint
	if !strings.Contains(out, "PRIMARY KEY (`id`)") {
		t.Error("MySQL: expected PRIMARY KEY (`id`)")
	}
	// Foreign key
	if !strings.Contains(out, "ALTER TABLE `posts` ADD CONSTRAINT `fk_posts_author_id` FOREIGN KEY (`author_id`) REFERENCES `authors` (`id`)") {
		t.Error("MySQL: expected ALTER TABLE foreign key statement")
	}
	// Index
	if !strings.Contains(out, "CREATE INDEX `idx_authors_username` ON `authors` (`username`)") {
		t.Error("MySQL: expected CREATE INDEX for indexed column")
	}
}

func TestGeneratePostgreSQL(t *testing.T) {
	out := generateSQL(t, blogSchema, DBMSPostgreSQL)

	// Identifier quoting
	if !strings.Contains(out, `"authors"`) {
		t.Error("PostgreSQL: expected double-quoted table name")
	}
	// GENERATED ALWAYS AS IDENTITY
	if !strings.Contains(out, "GENERATED ALWAYS AS IDENTITY") {
		t.Error("PostgreSQL: expected GENERATED ALWAYS AS IDENTITY")
	}
	// Type mappings
	if !strings.Contains(out, "VARCHAR(64)") {
		t.Error("PostgreSQL: expected VARCHAR(64)")
	}
	// Default string
	if !strings.Contains(out, "DEFAULT 'draft'") {
		t.Error("PostgreSQL: expected DEFAULT 'draft'")
	}
	// NOW() preserved
	if !strings.Contains(out, "DEFAULT NOW()") {
		t.Error("PostgreSQL: expected DEFAULT NOW()")
	}
	// Foreign key
	if !strings.Contains(out, `ALTER TABLE "posts" ADD CONSTRAINT "fk_posts_author_id" FOREIGN KEY ("author_id") REFERENCES "authors" ("id")`) {
		t.Error("PostgreSQL: expected ALTER TABLE foreign key statement")
	}
}

func TestGenerateMSSQL(t *testing.T) {
	out := generateSQL(t, blogSchema, DBMSMSSQL)

	// Identifier quoting
	if !strings.Contains(out, "[authors]") {
		t.Error("MSSQL: expected bracket-quoted table name")
	}
	// IDENTITY(1,1)
	if !strings.Contains(out, "IDENTITY(1,1)") {
		t.Error("MSSQL: expected IDENTITY(1,1)")
	}
	// varchar → NVARCHAR
	if !strings.Contains(out, "NVARCHAR(64)") {
		t.Error("MSSQL: expected NVARCHAR(64)")
	}
	// timestamp → DATETIME
	if !strings.Contains(out, "DATETIME") {
		t.Error("MSSQL: expected DATETIME")
	}
	// NOW() → GETDATE()
	if !strings.Contains(out, "DEFAULT GETDATE()") {
		t.Error("MSSQL: expected DEFAULT GETDATE()")
	}
}

func TestGenerateOracle(t *testing.T) {
	out := generateSQL(t, blogSchema, DBMSOracle)

	// Identifier quoting
	if !strings.Contains(out, `"authors"`) {
		t.Error("Oracle: expected double-quoted table name")
	}
	// GENERATED ALWAYS AS IDENTITY
	if !strings.Contains(out, "GENERATED ALWAYS AS IDENTITY") {
		t.Error("Oracle: expected GENERATED ALWAYS AS IDENTITY")
	}
	// bigint → NUMBER(19)
	if !strings.Contains(out, "NUMBER(19)") {
		t.Error("Oracle: expected NUMBER(19) for bigint")
	}
	// varchar → VARCHAR2
	if !strings.Contains(out, "VARCHAR2(64)") {
		t.Error("Oracle: expected VARCHAR2(64)")
	}
	// NOW() → SYSDATE
	if !strings.Contains(out, "DEFAULT SYSDATE") {
		t.Error("Oracle: expected DEFAULT SYSDATE")
	}
}

func TestGenerateSQLite(t *testing.T) {
	out := generateSQL(t, blogSchema, DBMSSQLite)

	// Identifier quoting
	if !strings.Contains(out, `"authors"`) {
		t.Error("SQLite: expected double-quoted table name")
	}
	// INTEGER PRIMARY KEY AUTOINCREMENT inline
	if !strings.Contains(out, `"id" INTEGER PRIMARY KEY AUTOINCREMENT`) {
		t.Error("SQLite: expected inline INTEGER PRIMARY KEY AUTOINCREMENT")
	}
	// No separate ALTER TABLE FK (SQLite FK is inline)
	if strings.Contains(out, "ALTER TABLE") {
		t.Error("SQLite: unexpected ALTER TABLE (SQLite uses inline FK)")
	}
	// Inline FOREIGN KEY constraint
	if !strings.Contains(out, `FOREIGN KEY ("author_id") REFERENCES "authors" ("id")`) {
		t.Error("SQLite: expected inline FOREIGN KEY constraint")
	}
	// PRAGMA foreign_keys
	if !strings.Contains(out, "PRAGMA foreign_keys = ON") {
		t.Error("SQLite: expected PRAGMA foreign_keys = ON")
	}
	// NOW() → CURRENT_TIMESTAMP
	if !strings.Contains(out, "DEFAULT CURRENT_TIMESTAMP") {
		t.Error("SQLite: expected DEFAULT CURRENT_TIMESTAMP")
	}
}

func TestGenerateNoLinks(t *testing.T) {
	src := `table users (
  id   bigint      primary-key
  name varchar(255) not-null
)`
	out := generateSQL(t, src, DBMSMySQL)
	if strings.Contains(out, "ALTER TABLE") {
		t.Error("expected no ALTER TABLE when there are no links")
	}
	if strings.Contains(out, "PRAGMA") {
		t.Error("expected no PRAGMA when there are no links")
	}
}

func TestGenerateTypeMapping(t *testing.T) {
	src := `table types (
  a bool
  b boolean
  c text
  d double
  e blob
  f json
  g uuid
)`

	cases := []struct {
		dbms DBMS
		want []string
	}{
		{DBMSMySQL, []string{"TINYINT(1)", "TEXT", "DOUBLE", "BLOB", "JSON", "CHAR(36)"}},
		{DBMSPostgreSQL, []string{"BOOLEAN", "TEXT", "DOUBLE PRECISION", "BYTEA", "JSON", "UUID"}},
		{DBMSMSSQL, []string{"BIT", "NVARCHAR(MAX)", "FLOAT", "VARBINARY(MAX)", "NVARCHAR(MAX)", "UNIQUEIDENTIFIER"}},
		{DBMSOracle, []string{"NUMBER(1)", "CLOB", "FLOAT(126)", "BLOB", "CLOB", "CHAR(36)"}},
		{DBMSSQLite, []string{"INTEGER", "TEXT", "REAL", "BLOB", "TEXT", "TEXT"}},
	}

	for _, tc := range cases {
		out := generateSQL(t, src, tc.dbms)
		for _, want := range tc.want {
			if !strings.Contains(out, want) {
				t.Errorf("DBMS %s: expected %q in output:\n%s", tc.dbms, want, out)
			}
		}
	}
}

func TestGenerateSelfReferentialLink(t *testing.T) {
	src := `
table categories (
  id        bigint primary-key auto-increment
  parent_id bigint nullable
  name      varchar(128) not-null
)
link one categories.id to many categories.parent_id
`
	// MySQL: self-referential FK via ALTER TABLE
	out := generateSQL(t, src, DBMSMySQL)
	if !strings.Contains(out, "ALTER TABLE `categories` ADD CONSTRAINT `fk_categories_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`)") {
		t.Error("MySQL: expected self-referential ALTER TABLE FK")
	}

	// SQLite: self-referential FK inline
	out = generateSQL(t, src, DBMSSQLite)
	if !strings.Contains(out, `FOREIGN KEY ("parent_id") REFERENCES "categories" ("id")`) {
		t.Error("SQLite: expected inline self-referential FOREIGN KEY")
	}
}
