package sqlexport

import (
	"fmt"
	"strings"

	"github.com/headercat/erdn-lang/internal/ast"
)

// DBMS identifies the target database management system.
type DBMS string

const (
	DBMSMySQL      DBMS = "mysql"
	DBMSPostgreSQL DBMS = "postgresql"
	DBMSMSSQL      DBMS = "mssql"
	DBMSOracle     DBMS = "oracle"
	DBMSSQLite     DBMS = "sqlite"
)

// SupportedDBMS is the ordered list of supported DBMS identifiers.
var SupportedDBMS = []string{
	string(DBMSMySQL),
	string(DBMSPostgreSQL),
	string(DBMSMSSQL),
	string(DBMSOracle),
	string(DBMSSQLite),
}

// ValidDBMS reports whether name is a recognised DBMS identifier.
func ValidDBMS(name string) bool {
	for _, s := range SupportedDBMS {
		if s == name {
			return true
		}
	}
	return false
}

// Generate converts an erdn-lang AST into SQL DDL for the given DBMS.
func Generate(prog *ast.Program, dbms DBMS) string {
	g := &generator{dbms: dbms}
	return g.generate(prog)
}

type generator struct {
	dbms DBMS
}

func (g *generator) generate(prog *ast.Program) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "-- Generated by erdn-lang\n")
	fmt.Fprintf(&sb, "-- DBMS: %s\n", g.dbms)

	// SQLite requires a PRAGMA to enforce foreign key constraints.
	if g.dbms == DBMSSQLite && len(prog.Links) > 0 {
		sb.WriteString("\nPRAGMA foreign_keys = ON;\n")
	}

	// CREATE TABLE statements.
	for i, t := range prog.Tables {
		sb.WriteString("\n")
		if i > 0 {
			sb.WriteString("\n")
		}
		g.writeCreateTable(&sb, t, prog.Links)
	}

	// CREATE INDEX statements.
	hasIndexes := false
	for _, t := range prog.Tables {
		for _, col := range t.Columns {
			if g.hasModifier(col, ast.ModIndexed) {
				hasIndexes = true
				break
			}
		}
		if hasIndexes {
			break
		}
	}
	if hasIndexes {
		sb.WriteString("\n")
		for _, t := range prog.Tables {
			g.writeIndexes(&sb, t)
		}
	}

	// ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY … for non-SQLite databases.
	// SQLite FK constraints are declared inline inside CREATE TABLE.
	if g.dbms != DBMSSQLite && len(prog.Links) > 0 {
		sb.WriteString("\n")
		for _, l := range prog.Links {
			g.writeForeignKey(&sb, l)
		}
	}

	// Trim trailing newlines and add exactly one.
	return strings.TrimRight(sb.String(), "\n") + "\n"
}

// writeCreateTable writes a single CREATE TABLE statement.
func (g *generator) writeCreateTable(sb *strings.Builder, t *ast.Table, links []*ast.Link) {
	q := g.quote

	// Find the primary key column (if any).
	var pkCol *ast.Column
	for _, col := range t.Columns {
		if g.hasModifier(col, ast.ModPrimaryKey) {
			pkCol = col
			break
		}
	}

	fmt.Fprintf(sb, "CREATE TABLE %s (\n", q(t.Name))

	var lines []string
	for _, col := range t.Columns {
		lines = append(lines, g.columnDef(col))
	}

	// Table-level PRIMARY KEY constraint.
	// SQLite uses inline "INTEGER PRIMARY KEY [AUTOINCREMENT]", not a separate constraint.
	if pkCol != nil && g.dbms != DBMSSQLite {
		lines = append(lines, fmt.Sprintf("  PRIMARY KEY (%s)", q(pkCol.Name)))
	}

	// SQLite: emit FOREIGN KEY table constraints inline.
	if g.dbms == DBMSSQLite {
		for _, l := range links {
			if l.ToTable == t.Name {
				lines = append(lines, fmt.Sprintf("  FOREIGN KEY (%s) REFERENCES %s (%s)",
					q(l.ToColumn), q(l.FromTable), q(l.FromColumn)))
			}
		}
	}

	fmt.Fprintf(sb, "%s\n);\n", strings.Join(lines, ",\n"))
}

// writeIndexes writes CREATE INDEX statements for indexed columns in table t.
func (g *generator) writeIndexes(sb *strings.Builder, t *ast.Table) {
	q := g.quote
	for _, col := range t.Columns {
		if g.hasModifier(col, ast.ModIndexed) {
			idxName := fmt.Sprintf("idx_%s_%s", t.Name, col.Name)
			fmt.Fprintf(sb, "CREATE INDEX %s ON %s (%s);\n",
				q(idxName), q(t.Name), q(col.Name))
		}
	}
}

// writeForeignKey writes an ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY statement.
func (g *generator) writeForeignKey(sb *strings.Builder, l *ast.Link) {
	q := g.quote
	constraintName := fmt.Sprintf("fk_%s_%s", l.ToTable, l.ToColumn)
	fmt.Fprintf(sb, "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s);\n",
		q(l.ToTable), q(constraintName), q(l.ToColumn), q(l.FromTable), q(l.FromColumn))
}

// columnDef returns the SQL column definition line (with two-space indent).
func (g *generator) columnDef(col *ast.Column) string {
	q := g.quote

	isPK := g.hasModifier(col, ast.ModPrimaryKey)
	isAutoInc := g.hasModifier(col, ast.ModAutoIncrement)
	isNotNull := g.hasModifier(col, ast.ModNotNull)

	typePart := g.mapType(col.Type, col.TypeParams)

	// SQLite special case: INTEGER PRIMARY KEY [AUTOINCREMENT] is the canonical
	// rowid alias; it must be expressed inline, not as a table constraint.
	if g.dbms == DBMSSQLite && isPK {
		if isAutoInc {
			return fmt.Sprintf("  %s INTEGER PRIMARY KEY AUTOINCREMENT", q(col.Name))
		}
		return fmt.Sprintf("  %s INTEGER PRIMARY KEY", q(col.Name))
	}

	var colSB strings.Builder
	fmt.Fprintf(&colSB, "  %s %s", q(col.Name), typePart)

	// GENERATED ALWAYS AS IDENTITY / IDENTITY(1,1) immediately follows the type.
	if isAutoInc {
		switch g.dbms {
		case DBMSPostgreSQL, DBMSOracle:
			colSB.WriteString(" GENERATED ALWAYS AS IDENTITY")
		case DBMSMSSQL:
			colSB.WriteString(" IDENTITY(1,1)")
		}
	}

	// NOT NULL is required for primary key columns (even without an explicit modifier).
	if isNotNull || isPK {
		colSB.WriteString(" NOT NULL")
	}

	// DEFAULT value.
	for _, mod := range col.Modifiers {
		if mod.Kind == ast.ModDefault {
			fmt.Fprintf(&colSB, " DEFAULT %s", g.formatDefault(mod.Value))
			break
		}
	}

	// MySQL AUTO_INCREMENT appears at the end of the column definition.
	if isAutoInc && g.dbms == DBMSMySQL {
		colSB.WriteString(" AUTO_INCREMENT")
	}

	return colSB.String()
}

// quote wraps an identifier with the DBMS-appropriate quoting characters.
func (g *generator) quote(name string) string {
	switch g.dbms {
	case DBMSMySQL:
		return "`" + name + "`"
	case DBMSMSSQL:
		return "[" + name + "]"
	default: // PostgreSQL, Oracle, SQLite
		return `"` + name + `"`
	}
}

// formatDefault converts an erdn default value token to its SQL representation.
//
// erdn stores the raw content of default(…), e.g. "draft" (with double quotes)
// or NOW(). This function:
//   - Maps NOW() to the DBMS-specific current-timestamp function.
//   - Converts double-quoted string literals to single-quoted SQL strings.
//   - Passes numeric and other literals through unchanged.
func (g *generator) formatDefault(val string) string {
	if strings.EqualFold(val, "NOW()") {
		switch g.dbms {
		case DBMSMSSQL:
			return "GETDATE()"
		case DBMSOracle:
			return "SYSDATE"
		case DBMSSQLite:
			return "CURRENT_TIMESTAMP"
		default:
			return "NOW()"
		}
	}

	// Convert erdn double-quoted string literals to SQL single-quoted strings.
	if len(val) >= 2 && val[0] == '"' && val[len(val)-1] == '"' {
		return "'" + val[1:len(val)-1] + "'"
	}

	return val
}

// mapType returns the SQL type name for the given erdn type and optional parameters.
func (g *generator) mapType(typeName string, params []string) string {
	lower := strings.ToLower(typeName)
	paramStr := ""
	if len(params) > 0 {
		paramStr = "(" + strings.Join(params, ", ") + ")"
	}

	switch g.dbms {
	case DBMSMySQL:
		return mapTypeMySQL(lower, paramStr)
	case DBMSPostgreSQL:
		return mapTypePostgreSQL(lower, paramStr)
	case DBMSMSSQL:
		return mapTypeMSSQL(lower, params, paramStr)
	case DBMSOracle:
		return mapTypeOracle(lower, paramStr)
	case DBMSSQLite:
		return mapTypeSQLite(lower, paramStr)
	}
	return strings.ToUpper(typeName) + paramStr
}

func mapTypeMySQL(lower, paramStr string) string {
	switch lower {
	case "bigint":
		return "BIGINT"
	case "int", "integer":
		return "INT"
	case "smallint":
		return "SMALLINT"
	case "tinyint":
		return "TINYINT"
	case "varchar":
		return "VARCHAR" + paramStr
	case "char":
		return "CHAR" + paramStr
	case "text", "mediumtext", "longtext":
		return strings.ToUpper(lower)
	case "bool", "boolean":
		return "TINYINT(1)"
	case "timestamp":
		return "TIMESTAMP"
	case "datetime":
		return "DATETIME"
	case "date":
		return "DATE"
	case "time":
		return "TIME"
	case "float":
		return "FLOAT"
	case "double":
		return "DOUBLE"
	case "decimal", "numeric":
		return strings.ToUpper(lower) + paramStr
	case "blob":
		return "BLOB"
	case "json":
		return "JSON"
	case "uuid":
		return "CHAR(36)"
	}
	return strings.ToUpper(lower) + paramStr
}

func mapTypePostgreSQL(lower, paramStr string) string {
	switch lower {
	case "bigint":
		return "BIGINT"
	case "int", "integer":
		return "INT"
	case "smallint":
		return "SMALLINT"
	case "tinyint":
		return "SMALLINT"
	case "varchar":
		return "VARCHAR" + paramStr
	case "char":
		return "CHAR" + paramStr
	case "text", "mediumtext", "longtext":
		return "TEXT"
	case "bool", "boolean":
		return "BOOLEAN"
	case "timestamp":
		return "TIMESTAMP"
	case "datetime":
		return "TIMESTAMP"
	case "date":
		return "DATE"
	case "time":
		return "TIME"
	case "float":
		return "REAL"
	case "double":
		return "DOUBLE PRECISION"
	case "decimal", "numeric":
		return strings.ToUpper(lower) + paramStr
	case "blob":
		return "BYTEA"
	case "json":
		return "JSON"
	case "uuid":
		return "UUID"
	}
	return strings.ToUpper(lower) + paramStr
}

func mapTypeMSSQL(lower string, params []string, paramStr string) string {
	switch lower {
	case "bigint":
		return "BIGINT"
	case "int", "integer":
		return "INT"
	case "smallint":
		return "SMALLINT"
	case "tinyint":
		return "TINYINT"
	case "varchar":
		if len(params) > 0 {
			return "NVARCHAR" + paramStr
		}
		return "NVARCHAR(255)"
	case "char":
		if len(params) > 0 {
			return "NCHAR" + paramStr
		}
		return "NCHAR(1)"
	case "text", "mediumtext", "longtext":
		return "NVARCHAR(MAX)"
	case "bool", "boolean":
		return "BIT"
	case "timestamp", "datetime":
		return "DATETIME"
	case "date":
		return "DATE"
	case "time":
		return "TIME"
	case "float":
		return "REAL"
	case "double":
		return "FLOAT"
	case "decimal", "numeric":
		return strings.ToUpper(lower) + paramStr
	case "blob":
		return "VARBINARY(MAX)"
	case "json":
		return "NVARCHAR(MAX)"
	case "uuid":
		return "UNIQUEIDENTIFIER"
	}
	return strings.ToUpper(lower) + paramStr
}

func mapTypeOracle(lower, paramStr string) string {
	switch lower {
	case "bigint":
		return "NUMBER(19)"
	case "int", "integer":
		return "NUMBER(10)"
	case "smallint":
		return "NUMBER(5)"
	case "tinyint":
		return "NUMBER(3)"
	case "varchar":
		return "VARCHAR2" + paramStr
	case "char":
		return "CHAR" + paramStr
	case "text", "mediumtext", "longtext":
		return "CLOB"
	case "bool", "boolean":
		return "NUMBER(1)"
	case "timestamp", "datetime":
		return "TIMESTAMP"
	case "date":
		return "DATE"
	case "time":
		return "INTERVAL DAY TO SECOND"
	case "float":
		return "FLOAT"
	case "double":
		return "FLOAT(126)"
	case "decimal", "numeric":
		return "NUMBER" + paramStr
	case "blob":
		return "BLOB"
	case "json":
		return "CLOB"
	case "uuid":
		return "CHAR(36)"
	}
	return strings.ToUpper(lower) + paramStr
}

func mapTypeSQLite(lower, paramStr string) string {
	switch lower {
	case "bigint", "int", "integer", "smallint", "tinyint", "bool", "boolean":
		return "INTEGER"
	case "varchar", "char", "text", "mediumtext", "longtext",
		"timestamp", "datetime", "date", "time", "json", "uuid":
		return "TEXT"
	case "float", "double", "real":
		return "REAL"
	case "decimal", "numeric":
		return "NUMERIC" + paramStr
	case "blob":
		return "BLOB"
	}
	return strings.ToUpper(lower)
}

// hasModifier reports whether col has a modifier of the given kind.
func (g *generator) hasModifier(col *ast.Column, kind ast.ModifierKind) bool {
	for _, mod := range col.Modifiers {
		if mod.Kind == kind {
			return true
		}
	}
	return false
}
